name: Website

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish the website?
        required: true
        default: false
        type: boolean
  workflow_call:
    inputs:
      publish:
        required: false
        default: false
        type: boolean

jobs:

  #
  # Build website
  #
  website-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "::set-output name=publish::${{ github.event.inputs.publish || inputs.publish }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin
          pip install mkdocs-macros-plugin
      - name: Step to start local HTTP server with Fragnova docs
        run: nohup mkdocs serve > nohup.out 2> nohup.err < /dev/null &
      - name: Step to sleep for 5 seconds
        run: sleep 5s
      - name: Step to check for broken links
        id: link-report
        uses: roc/link-checker@master
        with:
          url: "http://127.0.0.1:8000"
          blc_args: --recursive --verbose --follow true
          allow_failures: false
      - name: Build website
        if: ${{ steps.setup.outputs.publish != 'true' }}
        run: |
          mkdocs build
      - name: Build & publish website
        if: ${{ steps.setup.outputs.publish == 'true' }}
        run: |
          git config --global user.name "Fragcolor bot"
          git config --global user.email "bot@fragcolor.xyz"
          mkdocs gh-deploy --force --message "Publish documentation from {sha}
          
          Using MkDocs {version}."
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            site/
          if-no-files-found: error
