name: Website

on:
  workflow_dispatch:

jobs:

  #
  # Build website
  #
  website-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin
      - name: Build website
        run: |
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            site/
          if-no-files-found: error

  #
  # Publish website to IPFS
  #
  website-publish:
    needs: website-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install ipfs-car
        run: |
          npm install -g ipfs-car
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: website
          path: site
      - name: Publish to NFT storage
        run: |
          ipfs-car --pack site --output chainblocks-examples.car
          curl -X POST https://api.nft.storage/upload \
               --data-binary @chainblocks-examples.car \
               -H "Authorization: Bearer ${{ secrets.NFT_STORAGE_KEY }}" \
               -H "Content-Type: application/car" \
               > response.json
          cat response.json
          if [ $(cat response.json | jq .ok) != "true" ]; then exit 1; fi
